language: php
env:
  global:
    - GLPI_URL="http://localhost/glpi/apirest.php/"
    - GLPI_SOURCE="https://github.com/glpi-project/glpi -b 9.2/bugfixes"

before_script:
  - mysql -u root -e 'create database glpitest;'
  - phpenv config-rm xdebug.ini || true
  - rm -f composer.lock
  - git clone --depth=1 $GLPI_SOURCE ../glpi && cd ../glpi
  - composer install --no-dev --no-interaction
  - php tools/cliinstall.php --db=glpitest --user=root --tests
  - cd ../composer-package-glpi && composer install --no-interaction

script:
  - vendor/bin/atoum --debug -bf tests/bootstrap.php -no-cc --max-children-number 1 -d tests/unit
  - if [[ "$CS" == "true" ]]; then vendor/bin/phpcs -p --standard=vendor/glpi-project/coding-standard/GlpiStandard/ src/ tests/; fi

matrix:
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
      env: CS=true
    - php: nightly
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache
    
notifications:
  webhooks: https://hooks.aethonan.pro/travisci/-1001061475099/
